# Generated by Django 5.0.6 on 2025-01-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
